site:
  title: 稀土掘金
  description: 稀土掘金
  keywords: 稀土掘金, git, gitsite, javascript, node, jquery, python, java, spring, sql, database, linux, operating system, os, cpu, verilog, risc-v, bitcoin, ethereum, ai, 教程, 软件, 编程, 开发, 运维, 云计算, 网络, 互联网, 比特币, 以太坊, 操作系统, 智能合约, 数字货币
  theme: default
  language: zh-CN
  # set the /<rootPath> pathname under which your site is served
  # for GitHub pages deployment without a custom domain, it is often '/<projectName>'
  # root-path: /gitsite
  # set cdn prefix: self hosted
  cdn-path: /static
  navigation:
    - title: Java教程
      uri: /books/java/index.html
    - title: Python教程
      uri: /books/python/index.html
    - title: JavaScript教程
      uri: /books/javascript/index.html
    - title: SQL教程
      uri: /books/sql/index.html
    - title: 手写Spring
      uri: /books/summerframework/index.html
    - title: 手写Tomcat
      uri: /books/jerrymouse/index.html
    - title: 区块链教程
      uri: /books/blockchain/index.html
    - title: Git教程
      uri: /books/git/index.html
    - title: Makefile教程
      uri: /books/makefile/index.html
    - title: 博客
      uri: /blogs/all/index.html
  git:
    base-url: https://github.com/lifengdi/techblog/blob/main/source
  contact:
    name: Daryl
    github: https://github.com/lifengdi/techblog
    twitter: https://twitter.com/
  books:
    index-marker: true
  search:
    # none = no search
    # browser = flex search in browser
    # google = google site search
    type: browser
  # control styles:
  styles:
    # show 'Edit in Git':
    display-git-link: false
    # any custom styles used in theme:
    # code-font: Monaco
  integration:
    comment:
#      provider: oauth
#      url: https://api.liaoxuefeng.com
    analytics:
#      provider: baidu
#      id: "2efddd14a5f2b304677462d06fb4f964"
  footer: |
          <div>
            &copy;<a href="/">xitujuejin.online</a> 
            - <a href="https://github.com/lifengdi" target="_blank">GitHub</a>
          </div>


build:
  # copy special files under root dir (ignore if not found):
  copy:
    - favicon.ico
    - robots.txt
    - ads.txt

# you can add any items:
